language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI=true
deploy:
  provider: heroku
  api_key:
    secure: eDxTB4m51HGjPbSd5b1VfYSNHlp6Er2jmK7YWB//cya9c6ud214Fltcrv9PAY2lMB+KwWjLgSJkpEZsrs9uEy0ZB+JWMZfkDuTqELuH0JgIb4eIsYbx7LQ9wvVpb2NhPb4AxAVgqAj/64zD+5J2oUzKAmX2mbXkDNP8yDXzuCdxUsif2eV7L1Aq1o8LAiKBTSQ6xjRUlZC4MBrN6aeK9CWBkTihi2FJ4MThgWSXFeR7EVmS3I47LNkN/pvt8C7RYZsfTdd6M3BQKBSGeKVtc17aW5Y7xjD7yWa0F3P0mG9GsEw/RMzNnsJlWH7vo3CtP+rOJeKCDEkOtlEINhCRHlZBM/Gj3VxPWbZU027FfFTyrkYVDverNTk6kDwBTVYKSSgTJmIWnVr89Xbx6vg8MtxP9lsRdoZncv9IVI8iMRv5KgCAVZ2hIic5jD2m/uk/ssCMTqYS7G2B8QdWcFeFHcXrnO4Knv6OEifpMAOYTCAfGxQaEYQOUgY1BFId01z+8vg3Grye3TaXo7FWCWUXwtCUy7bZ7q/JDN3IaIzKdDVLyYjW+CwY+9W3+xydejd+gXC70ZREkUxmANVoUwhgfwqHFewBzqOYAdzXP/fks96fKmne5SoV2rrpxhosGWKiGXQB/TC9gmELX4n/pmPk9QRNkHICuIcfq5tmPEim21ho=
  app: sputnikapp
  on:
    repo: rcmaples/sputnikapp
branches:
  except:
    - development
