language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI=true
deploy:
  provider: heroku
  api_key:
    secure: seATJitryx2QhPAarVmiIrdC45LuK9zEBbQKLoroiPOouhoFr2lQ5EiGRMcFZAggg/iM9+9aHGmsayZg4knBNn3nfAgJPgkqYnDnwjrEusluWiAbInEhOuZJ9N3Bg8ZIWn/lPZ5/UcdNils1HUkoGTmeW9AzdhykOCePFsBZBBX1WXIBAP2gs09lZtXhIFmj4LMUIcbxf2WPFlCCi8Kfb9Ao7XFkw0AUTEojowhmEdxHfrCLKNMqA31FX63+RKpOaeR8A1nGqBSX9hH/o0C+FZ728yMkBBZwUTXbsb0PSlTOCgIRVTEvu5Ta3Z7nJiphS9rS0bqmkTiuGSozke9Q1DKIzu2XCI5XRB44mqxmpqJ0YzI6FeEISVaZcH+g4EKwd6z+RNNudFMzevhNfyiGL8iARxU2thdYf9Gta/M/9GyCHGMsccmG7qC9f09Y8L0fGWI18JiHP//Xp7kgb+NLKvot6wUwMlJKaEeb4Cp+pUheMiHOnx6oYGQ0UmtKCxhbWN0MA5o20qg0uvC9AlXIKj8BqJ302ctikI/9M0s2UGTcZ87LSVu1wjrqNzdevG7yqjcIu2Vtnl3+pDSEwXDIBePgEil/+axZl20cZE68KOmaMMwSfO2vw89u4uEejBcm6Cujm2gZnLPOyUNHSFNLQd9hdNcILv2XJco7sxqSCRI=
  app: sputnikapp
  on:
    repo: rcmaples/sputnikapp
